### ISSUE TITLE
Opening beta version 3.0.13.0 on XrmToolBox version 1.2016.5.27 throws script error

### ISSUE THREAD

**Issue by mscottsewell** [scottdurow/RibbonWorkbench#1]
First!  :grinning:

![ribbon workbench error](https://cloud.githubusercontent.com/assets/6276300/16356069/d6057ac0-3a99-11e6-8c4c-90769e5b64d0.png)
Then:
![image](https://cloud.githubusercontent.com/assets/6276300/16356070/e06aecc0-3a99-11e6-80a1-868ce91945b9.png)

**Comment by scottdurow** [comment]
Hi Scott,
This is odd – that's not even my plugin!
Maybe this is one for Tanguy since it looks like one plugin is interfering with the others.
I suggest you use the CRM solution beta version for now, or unload the User settings plugin first.

**Comment by scottdurow** [comment]
It seems to be caused by DLab Tools Plugin - if you delete this one you should be able to start the Ribbon Workbench Plugin ok.

**Comment by mscottsewell** [comment]
Yes, I deleted the other plugin - but the two shouldn't interfere with the other - 

![image](https://cloud.githubusercontent.com/assets/6276300/16357026/e91d8bb0-3ab8-11e6-9c93-b647741c836f.png)

**Comment by scottdurow** [comment]
Totally agree - Tanguy is going to issue some guidance on writing plugins so that they don't interfere with others.

**Comment by mscottsewell** [comment]
Thanks - have a great weekend  - or is it now known as a #Weekexit ?  ;-)

**Comment by scottdurow** [comment]
I've updated the Ribbon Workbench plugin to work around the issue - so you should be able to have both plugins loaded now :)

**Comment by mscottsewell** [comment]
Yep - thanks - works great!
