### ISSUE TITLE
Tool unusable when providing wrong resource name

### ISSUE THREAD

**Issue by LeszekSzejka** [scottdurow/RibbonWorkbench#16]
When providing a wrong webResource name,(eg. via copy-paste) there is an exception that JS script has stopped on this website and tool becomes unusable.

![scriptissue](https://cloud.githubusercontent.com/assets/13485243/25275043/8187bc42-2693-11e7-8929-5fc40bee64bd.png)

**Comment by scottdurow** [comment]
I can't seem to reproduce this - could you provide some steps?
