### ISSUE TITLE
Smart Buttons in XRMToolbox

### ISSUE THREAD

**Issue by aboodh95** [scottdurow/RibbonWorkbench#17]
Is there any chance smart button will be implemented in XRMToolbox

**Comment by scottdurow** [comment]
Smart buttons are now in XrmToolbox as of version 1.2.85.1

**Comment by aboodh95** [comment]
you mean RibbonWorkbench 1.2.85.1 
because the update had the version 3.1.86.1

**Comment by aboodh95** [comment]
![image](https://user-images.githubusercontent.com/12459798/30251862-5980dd18-9679-11e7-9485-8dbee7d7f425.png)

after update

**Comment by scottdurow** [comment]
Hi,
You're right - it's version 3.1.86.1 with the Smart Buttons solution 1.2.85.1
You will need to install the Smart Buttons solution inside your target Dynamics instance - the XrmToolbox RibbonWorkbench now supports using them once installed!

See https://ribbonworkbench.uservoice.com/knowledgebase/articles/896958-smart-buttons

Thanks!

**Comment by aboodh95** [comment]
Thank you
