### ISSUE TITLE
Add a 'Close' option to allow you to close the ribbon editor tab.

### ISSUE THREAD

**Issue by mscottsewell** [scottdurow/RibbonWorkbench#2]
Currently you can only close the ribbon workbench by closing the whole XrmToolbox - other plugins allow you to close without killing the whole toolbox.

**Comment by scottdurow** [comment]
Hi Scott,
You can use the 'Tabs->Close Current Tab' menu item.
I think a good suggestion for the XrmToolbox would be to provide a 'x' close button on the tab header it's self - the same as Visual Studio does.
