### ISSUE TITLE
Smart Button "Run Workflow" does not show in Unified Client

### ISSUE THREAD

**Issue by pahansen** [scottdurow/RibbonWorkbench#31]
I'm using the latest version of the smart button solution but smart buttons will not show in the unified client even though I've deleted the display rules from the command. Any suggestions on how to resolve this?

Thanks a lot!

**Comment by scottdurow** [comment]
Have you followed the steps on https://www.develop1.net/public/post/2018/04/06/Adding-Ribbon-Workbench-SmartButtons-to-the-Unified-Client
