### ISSUE TITLE
Duplicate buttons with no commands

### ISSUE THREAD

**Issue by foleyp** [scottdurow/RibbonWorkbench#4]
After importing a managed solution into an existing 2016 CRM organisation we are noticing there are duplicate buttons that the ribbon workbench shows with labels like $LocLabels:asic.incident.UnitTest.Button.LabelText (we always just use fixed strings) and no commands. Have you any idea why this is happening? How to fix?

**Comment by scottdurow** [comment]
Hi,
Managed solutions will not show up with commands and labels since they cannot be edited. To see the buttons and command you'll need to use the Ribbon Workbench on your unmanaged environment.
