### ISSUE TITLE
Cannot open the RibbonWorkbench in XRMToolBox

### ISSUE THREAD

**Issue by aboodh95** [scottdurow/RibbonWorkbench#40]
Hi,

After the new update of XRMToolBox, i cannot open the RibbonWorkbench and i'm getting the error
![image](https://user-images.githubusercontent.com/12459798/59247778-81c57b80-8c31-11e9-8842-50d5c6d56015.png)
as one of the new feature in the lateset XRMToolBox update was
![image](https://user-images.githubusercontent.com/12459798/59247867-cfda7f00-8c31-11e9-9f54-c22818aae2f4.png)

**Comment by scottdurow** [comment]
You will need to update to the latest version of the RWB.

**Comment by aboodh95** [comment]
it's not showing any update in the plugin store

**Comment by scottdurow** [comment]
Hmm - I don't know what that is. The latest version in Nuget is 3.1.325.1

https://www.nuget.org/packages/RibbonWorkbench2016/

**Comment by aboodh95** [comment]
Hi,

I meant XRMToolBox Store, thanks for the link
