### ISSUE TITLE
Run Workflow in D365 (9.1.0.10733)

### ISSUE THREAD

**Issue by squiso** [scottdurow/RibbonWorkbench#44]
Hi, thanks for the great solution. Are there any plans to update the current smart buttons to use Web API?

**Comment by scottdurow** [comment]
Yes! Before 2020!

**Comment by squiso** [comment]
That would be amazing! It should simply the code quite a bit as well. 

Can I please put in a feature request while you do this to support accessing the error message from a synchronous workflow in the error callback. When you have cancellation/error messages that prevents the workflow completing its nice to able to present the error back to the user without having them need to inspect the workflow. 

See example where I've made the error callback generic but would prefer to include the actual message from the workflow.

![image](https://user-images.githubusercontent.com/6523494/70842861-0bc6f900-1e8e-11ea-9396-6c52ac38d808.png)
