### ISSUE TITLE
Smart Buttons: Run Workflow (v1.2.381.1)

### ISSUE THREAD

**Issue by rcl43** [scottdurow/RibbonWorkbench#45]
There seems to be an issue with the "Start Workflow Confirmation Text" not showing in the classic UI. The message shows just fine in the UCI. 

I did check the page elements and the message does seem to be there, it's just not displaying. I've attached images of the UCI and Classic UI results as well as the Smart Button Config. 
![RunWorkflowFormButtonConfig](https://user-images.githubusercontent.com/17263869/71374347-03527a80-2580-11ea-9903-34903108f582.png)
![ClassicUIBug](https://user-images.githubusercontent.com/17263869/71374348-03527a80-2580-11ea-91cb-6b7efb9efa5a.png)
![UCIConfirmationDialog](https://user-images.githubusercontent.com/17263869/71374349-03527a80-2580-11ea-9d78-5f2fe98baee3.png)

**Comment by rcl43** [comment]
P.S. I've also confirmed that this is the case in other modern browsers as well.

**Comment by scottdurow** [comment]
The new version of Smart Buttons is not supported in the Classic UI since it will not be around for much longer!
