### ISSUE TITLE
Canvas App Dialog - Fetching the selected GUID Task recordID

### ISSUE THREAD

**Issue by MrFearLess98** [scottdurow/RibbonWorkbench#61]
Hello,

Thank you for providing the smart buttons features.

I am trying to create custom Dialogs in Model-Driven Apps using Canvas Apps and the smart button "Open dialog".

[ Create custom Dialogs in Model-Driven Apps using Canvas Apps](https://community.dynamics.com/crm/b/develop1/posts/new-smart-button-custom-dialogs-in-model-driven-apps-using-canvas-apps#)

I am struggling on the OnStart event of this application to find a way to get the selected Task GUID ID from the URL without hardcoding the values. I want the app to parse this GUID ID from the URL and fetch it.

The below screenshot shows the task id parameter:
![Capture](https://user-images.githubusercontent.com/52073639/104622757-553dd500-569a-11eb-872c-0c5b40b442b5.PNG)

Can please someone explains in detail and provide an example to solve the above?

Best regards,
Julien

**Comment by scottdurow** [comment]
Hi @MrFearLess98  - When the smart button is run, it will use the selected record (only a single record can be used) and pass the ID on the URL to the Canvas App as recordId - you can then pick it up in the app using:
`GUID(Param("recordId")`

**Comment by MrFearLess98** [comment]
Hello @scottdurow ,

Ahh, I did not know that the smart button will save the record and fetch the GUID.

Now it works as expected, and thank you for providing a great way to create popups with LOW CODE solutions.

Keep going on! I will definitely discover more options using Smart Buttons.

Best regards,
Julien
