### ISSUE TITLE
Please remove the check for additional components. This check is very anoying

### ISSUE THREAD

**Issue by martintoelk** [scottdurow/RibbonWorkbench#64]
Please remove the check for additional components. This check is very anoying

---
- Deployment: Online
- DB Version: 9.1.0.24345
- Connection Controls Version: 1.2021.1.39
- XrmToolBox Version: 1.2020.11.42
- Tool Version: 3.1.392.1

**Comment by scottdurow** [comment]
Hi @martintoelk - I do understand it can be frustrating having to create a solution just for your ribbon edits - but it has always been best practice. Many were not following the advice and it was causing the export/import to be slow/fail/timeout so I decided to enforce the recommendation.

Hope you understand.

**Comment by martintoelk** [comment]
Okay, thanks for confirmation. I could understand now the decision. 

BR

Martin
